// const { PrismaClient } = require("@prisma/client");
// const prisma = new PrismaClient();


// const data = [
//   {
//     "name": "Aarav Singh",
//     "party": "Indian National Congress",
//     "state": "Uttar Pradesh",
//     "constituency": "Lucknow",
//     "age": 52,
//     "gender": "Male",
//     "education": "MA Political Science",
//     "criminalCases": 1,
//     "totalAssets": 3.5,
//     "position": "MP",
//     "biography": "A seasoned leader focused on education reform.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 8.5,
//     "ratingsOutOf": 10,
//     "numOfSearched": 115
//   },
//   {
//     "name": "Priya Deshmukh",
//     "party": "Bharatiya Janata Party",
//     "state": "Maharashtra",
//     "constituency": "Pune",
//     "age": 45,
//     "gender": "Female",
//     "education": "MBA",
//     "criminalCases": 0,
//     "totalAssets": 12.8,
//     "position": "MLA",
//     "biography": "Focused on women's empowerment and tech growth.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 9.1,
//     "ratingsOutOf": 10,
//     "numOfSearched": 232
//   },
//   {
//     "name": "Ravi Menon",
//     "party": "Aam Aadmi Party",
//     "state": "Kerala",
//     "constituency": "Ernakulam",
//     "age": 38,
//     "gender": "Male",
//     "education": "B.Tech",
//     "criminalCases": 0,
//     "totalAssets": 2.3,
//     "position": "MLA",
//     "biography": "Young leader advocating digital literacy.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 9.7,
//     "ratingsOutOf": 10,
//     "numOfSearched": 183
//   },
//   {
//     "name": "Sunita Reddy",
//     "party": "Telugu Desam Party",
//     "state": "Andhra Pradesh",
//     "constituency": "Vijayawada",
//     "age": 60,
//     "gender": "Female",
//     "education": "BA",
//     "criminalCases": 2,
//     "totalAssets": 6.4,
//     "position": "MP",
//     "biography": "Focused on rural development and agriculture.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 7.8,
//     "ratingsOutOf": 10,
//     "numOfSearched": 98
//   },
//   {
//     "name": "Imran Qureshi",
//     "party": "Samajwadi Party",
//     "state": "Uttar Pradesh",
//     "constituency": "Varanasi",
//     "age": 49,
//     "gender": "Male",
//     "education": "MA Sociology",
//     "criminalCases": 3,
//     "totalAssets": 4.1,
//     "position": "MLA",
//     "biography": "Community leader supporting youth employment.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 6.2,
//     "ratingsOutOf": 10,
//     "numOfSearched": 64
//   },
//   {
//     "name": "Kavita Joshi",
//     "party": "Indian National Congress",
//     "state": "Himachal Pradesh",
//     "constituency": "Shimla",
//     "age": 41,
//     "gender": "Female",
//     "education": "PhD in Environmental Science",
//     "criminalCases": 0,
//     "totalAssets": 8.2,
//     "position": "MP",
//     "biography": "Works for environmental policy change.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 9.9,
//     "ratingsOutOf": 10,
//     "numOfSearched": 195
//   },
//   {
//     "name": "Suresh Patel",
//     "party": "Bharatiya Janata Party",
//     "state": "Gujarat",
//     "constituency": "Ahmedabad",
//     "age": 55,
//     "gender": "Male",
//     "education": "LLB",
//     "criminalCases": 1,
//     "totalAssets": 15.7,
//     "position": "MP",
//     "biography": "Experienced policymaker on trade and law.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 8.3,
//     "ratingsOutOf": 10,
//     "numOfSearched": 145
//   },
//   {
//     "name": "Neha Sharma",
//     "party": "Aam Aadmi Party",
//     "state": "Delhi",
//     "constituency": "New Delhi",
//     "age": 37,
//     "gender": "Female",
//     "education": "MBA",
//     "criminalCases": 0,
//     "totalAssets": 5.9,
//     "position": "MLA",
//     "biography": "Focused on education and public health.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 9.6,
//     "ratingsOutOf": 10,
//     "numOfSearched": 267
//   },
//   {
//     "name": "Aditya Verma",
//     "party": "Independent",
//     "state": "Bihar",
//     "constituency": "Patna",
//     "age": 50,
//     "gender": "Male",
//     "education": "BCom",
//     "criminalCases": 2,
//     "totalAssets": 3.2,
//     "position": "MP",
//     "biography": "Independent voice for infrastructure growth.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 7.0,
//     "ratingsOutOf": 10,
//     "numOfSearched": 76
//   },
//   {
//     "name": "Meera Banerjee",
//     "party": "Trinamool Congress",
//     "state": "West Bengal",
//     "constituency": "Kolkata South",
//     "age": 58,
//     "gender": "Female",
//     "education": "MA Literature",
//     "criminalCases": 0,
//     "totalAssets": 9.4,
//     "position": "MP",
//     "biography": "Author turned politician, strong advocate for arts.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 9.2,
//     "ratingsOutOf": 10,
//     "numOfSearched": 132
//   },
//   {
//     "name": "Rohan Kapoor",
//     "party": "Indian National Congress",
//     "state": "Punjab",
//     "constituency": "Ludhiana",
//     "age": 46,
//     "gender": "Male",
//     "education": "MBA",
//     "criminalCases": 1,
//     "totalAssets": 6.1,
//     "position": "MLA",
//     "biography": "Business leader advocating industrial growth.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 8.4,
//     "ratingsOutOf": 10,
//     "numOfSearched": 88
//   },
//   {
//     "name": "Anjali Iyer",
//     "party": "DMK",
//     "state": "Tamil Nadu",
//     "constituency": "Chennai Central",
//     "age": 43,
//     "gender": "Female",
//     "education": "MSc Computer Science",
//     "criminalCases": 0,
//     "totalAssets": 4.8,
//     "position": "MP",
//     "biography": "Technocrat focused on digital governance.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 9.3,
//     "ratingsOutOf": 10,
//     "numOfSearched": 202
//   },
//   {
//     "name": "Vikram Shetty",
//     "party": "Shiv Sena",
//     "state": "Maharashtra",
//     "constituency": "Thane",
//     "age": 59,
//     "gender": "Male",
//     "education": "BA",
//     "criminalCases": 3,
//     "totalAssets": 7.5,
//     "position": "MLA",
//     "biography": "Veteran leader in urban infrastructure.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 7.6,
//     "ratingsOutOf": 10,
//     "numOfSearched": 110
//   },
//   {
//     "name": "Farah Khan",
//     "party": "Independent",
//     "state": "Telangana",
//     "constituency": "Hyderabad",
//     "age": 39,
//     "gender": "Female",
//     "education": "LLM",
//     "criminalCases": 0,
//     "totalAssets": 2.9,
//     "position": "MP",
//     "biography": "Legal rights activist for minorities.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 8.7,
//     "ratingsOutOf": 10,
//     "numOfSearched": 158
//   },
//   {
//     "name": "Rajat Thakur",
//     "party": "BJP",
//     "state": "Madhya Pradesh",
//     "constituency": "Bhopal",
//     "age": 53,
//     "gender": "Male",
//     "education": "BSc",
//     "criminalCases": 1,
//     "totalAssets": 10.1,
//     "position": "MP",
//     "biography": "Champion of infrastructure and housing reform.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 8.0,
//     "ratingsOutOf": 10,
//     "numOfSearched": 142
//   },
//   {
//     "name": "Ishita Roy",
//     "party": "Trinamool Congress",
//     "state": "West Bengal",
//     "constituency": "Howrah",
//     "age": 34,
//     "gender": "Female",
//     "education": "MA Public Admin",
//     "criminalCases": 0,
//     "totalAssets": 5.6,
//     "position": "MLA",
//     "biography": "Focused on clean city initiatives and sanitation.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 9.5,
//     "ratingsOutOf": 10,
//     "numOfSearched": 174
//   },
//   {
//     "name": "Devendra Solanki",
//     "party": "BJP",
//     "state": "Rajasthan",
//     "constituency": "Jaipur",
//     "age": 61,
//     "gender": "Male",
//     "education": "MCom",
//     "criminalCases": 2,
//     "totalAssets": 13.6,
//     "position": "MLA",
//     "biography": "Working to modernize urban transportation.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 7.2,
//     "ratingsOutOf": 10,
//     "numOfSearched": 121
//   },
//   {
//     "name": "Tanya Kaul",
//     "party": "Indian National Congress",
//     "state": "Jammu & Kashmir",
//     "constituency": "Srinagar",
//     "age": 40,
//     "gender": "Female",
//     "education": "MA International Relations",
//     "criminalCases": 0,
//     "totalAssets": 4.4,
//     "position": "MP",
//     "biography": "Strong advocate for peace and diplomacy.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 9.0,
//     "ratingsOutOf": 10,
//     "numOfSearched": 209
//   },
//   {
//     "name": "Yashwant Rao",
//     "party": "NCP",
//     "state": "Maharashtra",
//     "constituency": "Nagpur",
//     "age": 62,
//     "gender": "Male",
//     "education": "MA Economics",
//     "criminalCases": 3,
//     "totalAssets": 11.2,
//     "position": "MLA",
//     "biography": "Veteran in rural finance reforms.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 6.8,
//     "ratingsOutOf": 10,
//     "numOfSearched": 97
//   },
//   {
//     "name": "Sneha Pillai",
//     "party": "Aam Aadmi Party",
//     "state": "Goa",
//     "constituency": "Panaji",
//     "age": 36,
//     "gender": "Female",
//     "education": "MSc Chemistry",
//     "criminalCases": 0,
//     "totalAssets": 3.9,
//     "position": "MLA",
//     "biography": "Focusing on science education and clean beaches.",
//     "profileImage": "https://res.cloudinary.com/dffepahvl/image/upload/v1753534237/sdwv6uaqggpcnnufpmop.jpg",
//     "avgRatings": 9.8,
//     "ratingsOutOf": 10,
//     "numOfSearched": 149
//   }
// ]

// async function main() {
//     await prisma.politician.createMany({
//         data: data,
//         skipDuplicates: true // prevents errors if same `id` exists
//     });

//     console.log('✅ 20 politicians added successfully');
// }
// main()
//     .catch((e) => {
//         console.error(e);
//         process.exit(1);
//     })
//     .finally(async () => {
//         await prisma.$disconnect();
//     });
